sonar.organization=haribo015
sonar.projectKey=haribo015_PersonalLibrary
sonar.projectName=PersonalLibrary
sonar.projectVersion=0.1.0
sonar.sourceEncoding=UTF-8

sonar.sources=backend/app,frontend/src,gateway
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=backend/tests/**/*.py,frontend/src/**/*.spec.ts

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.pyo,**/.pytest_cache/**,frontend/dist/**,frontend/node_modules/**,frontend/.angular/**,frontend/src/**/*.spec.ts,backend/.venv/**,**/coverage.xml,**/pytest-report.xml
sonar.coverage.exclusions=backend/tests/**,**/__init__.py,frontend/src/main.ts,frontend/src/polyfills.ts
sonar.cpd.exclusions=backend/tests/**,frontend/src/polyfills.ts

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.xunit.reportPath=backend/pytest-report.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/personal-library/lcov.info
